In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
%matplotlib notebook

In [2]:
# En particular las soluciones vivirán en R^n, n=[10,20,50]
n = [10,20,50]
N = 20*n[0]
M = 17*n[0]
# The domain of x_i is [-10,10] 
lower = -5.12
upper = 5.12
# Create an initial population
def init_population(chromosomes=N,gens=M,varmin=lower,varmax=upper):
    '''
    ABLE TO GENERATE A NEW POPULATION.
    chromosomes int. Number of solutions in the population.
    gens int. Number of elements for every solution.
    varmin float. Lower bound of the variable.
    varmax float. Upper bound of the variable.
    
    RETURN
    init_pop array. A new population with shape (chromosomes,gens)
    '''
    init_pop = np.zeros((chromosomes,gens))
    for chromosome in range(chromosomes):
        init_pop[chromosome,:] = np.random.uniform(varmin,varmax,gens)
    return init_pop

In [3]:
init_pop = init_population()
print(init_pop[0])
print(f'Initial population shape: {init_pop.shape}\n')

[ 3.08504282  0.12335568  1.5712564  -3.98784193 -3.67652877 -3.22272073
 -1.09989156 -5.0158417  -4.44951551  2.22856953 -0.09926372 -0.58780225
  3.91057909  4.06678602 -3.17773237 -2.85771618  3.54371396  3.87889643
  3.03254518 -4.55773519  4.92285786 -3.61639831  1.44493577 -1.52044472
 -1.07297093 -1.99805876 -2.14312379 -4.30860119  4.68291416 -5.10694906
 -3.54960433 -4.44785101 -1.03354884 -3.53109155  0.00622157 -1.37677557
  3.92537296  0.64752618 -3.06072462 -0.69779601  2.77954456  3.79840241
 -4.34781806 -1.81245422 -1.73871918  1.61461996 -3.22985081  2.77448095
 -3.96048285 -4.52222639 -0.61478368 -3.18423005  3.27510581  0.49452218
  1.79491377  2.17188285 -4.91920197 -4.58853058 -5.02210986 -3.39172746
  0.55257718  1.0447526  -2.04182634  1.98249933 -3.22818453 -0.20497325
 -5.03986399 -1.45633192  2.96235502 -3.34988859 -3.24660978 -4.88307104
  2.94743879  2.98397288 -1.25279177 -1.02885363  1.49042564 -2.01067267
  1.03946681 -4.58199119 -3.9563959   3.9824691   3

In [4]:
# Our error function will be a sphere function
def error(x):
    return sum(x**2)

In [5]:
# Elitism
def evaluation(population,function):
    '''
    ABLE TO EVALUATE THE FUNCTION FOR EVERY CHROMOSOME IN THE POPULATION.
    population array. The set of solutions.
    function function. The error function
    
    RETURN
    qualities array. Every chromosome evaluated on fitness function.
    '''
    qualities = np.zeros(population.shape[0])
    for chromosome in range(population.shape[0]):
        qualities[chromosome] = function(population[chromosome,:])
    return qualities

In [6]:
evaluated = evaluation(init_pop,error)
evaluated

array([1579.08003867, 1569.9000605 , 1483.96823069, 1380.93461315,
       1547.56569874, 1663.89408677, 1453.71051327, 1385.33204192,
       1354.17043537, 1596.41559314, 1403.1246861 , 1379.02061116,
       1496.5068931 , 1368.35455424, 1595.90480389, 1383.24324069,
       1284.00413746, 1535.32586412, 1506.0817706 , 1249.8882138 ,
       1471.51908581, 1368.37658815, 1377.7624035 , 1645.81770814,
       1370.36769967, 1569.48521133, 1399.8190102 , 1320.20213163,
       1545.84183378, 1453.91434907, 1509.72568545, 1586.56803467,
       1502.25462264, 1523.57231041, 1396.60772239, 1414.33050019,
       1404.78511401, 1746.24936971, 1264.56626773, 1501.44728661,
       1534.94076984, 1197.98227594, 1301.63091593, 1410.47319449,
       1380.13383038, 1578.75998777, 1420.2170233 , 1465.73140841,
       1481.82859031, 1356.31356607, 1685.02198519, 1390.51760234,
       1591.25208276, 1632.63228887, 1584.71691596, 1470.43859655,
       1396.58493124, 1580.30338501, 1528.0487293 , 1499.39365

In [262]:
np.max(evaluated)

1778.8044575107972

In [276]:
# Selection
def selection(n_parents,population,evaluated):
    '''
    ABLE TO SELECT THE n_parents BESTS SOLUTIONS.
    n_parents int. Number of parents.
    population array. All solutions of a generation.
    evaluated array. Every solution evaluated on the fitness function.
    
    RETURN
    parents array. A set of (n_parents,gens).
    '''
    parents = np.empty((n_parents,population.shape[1]))
    evals = evaluated.copy()
    best_index = 0
    worst_index = 0
    for parent in range(n_parents):
        # Best (min) quality parents
        if parent in [x for x in range(n_parents)]:
            best_quality_index = np.where(np.min(evals) == evals)[0][0]
            worst_quality_index = np.where(np.max(evals) == evals)[0][0]
            parents[parent,:] = population[best_quality_index,:]
            evals[best_quality_index] = np.inf
            #print(min_quality_index)
    return parents,best_quality_index, worst_quality_index

In [8]:
n_parents = N//2
parents = selection(n_parents,init_pop,evaluated)
print(parents)
print(parents.shape)

[[ 4.86231467  2.17709949 -3.10584369 ... -3.41198701 -0.23518382
  -3.89451251]
 [-2.39455203  4.53153828 -0.38594851 ...  4.44712691 -0.07393341
  -3.34695484]
 [ 0.13819765  0.18995422  1.49813845 ...  4.33554532 -3.72467751
   0.09432344]
 ...
 [ 2.69054779 -2.10585591 -1.43639368 ... -2.59928095 -1.7866213
   1.45641047]
 [ 2.74837093  0.28073548  3.21898481 ...  1.38221916 -1.78567048
   0.04920921]
 [-0.43755145 -2.88836633 -0.80558233 ... -0.78670182  2.06415742
   0.24114148]]
(100, 170)


In [272]:
def termination_criteria(evaluated,e,iteration,itermax):
    '''
    THE ALGORITHM TERMINATES IF THE CRITERIA IS TRUE.
    '''
    return abs(np.max(evaluated) - np.min(evaluated)) <= e or iteration >= itermax

In [10]:
e = 1
pare= [5,80]
itermax = 10
iteration = 11

termination_criteria(pare,e,iteration,itermax)

True

In [53]:
# Crossover
def crossover(parents, cutoff_point=parents.shape[1]//2):
    childs = np.zeros(parents.shape)
    for i in range(0,a.shape[0],2):
        if i+1 < a.shape[0]:
            childs[i][:cut] = parents[i][:cut]
            childs[i][cut:] = parents[i+1][cut:]
            childs[i+1][:cut] = parents[i+1][:cut]
            childs[i+1][cut:] = parents[i][cut:]
    return childs

In [222]:
a = np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]))
b = np.array(([10,20,30,40],[50,60,70,80],[90,100,110,120],[130,140,150,160]))
childs = crossover(a)
childs

array([[ 1.,  2.,  7.,  8.],
       [ 5.,  6.,  3.,  4.],
       [ 9., 10., 15., 16.],
       [13., 14., 11., 12.]])

In [40]:
cut=a.shape[1]//2
for i in range(0,a.shape[0],2):
    if i+1 < a.shape[0]:
        b[i][:cut] = a[i][:cut]
        b[i][cut:] = a[i+1][cut:]
        b[i+1][:cut] = a[i+1][:cut]
        b[i+1][cut:] = a[i][cut:]
print(b)

[[ 1  2  7  8]
 [ 5  6  3  4]
 [ 9 10 15 16]
 [13 14 11 12]]


In [13]:
b[0][:2] = a[0][:2]
b[0][2:] = a[1][2:]
b[1][:2] = a[1][:2]
b[1][2:] = a[0][2:]
b

array([[  1,   2,   7,   8],
       [  5,   6,   3,   4],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [14]:
b[2][:2] = a[2][:2]
b[2][2:] = a[3][2:]
b[3][:2] = a[3][:2]
b[3][2:] = a[2][2:]
b

array([[ 1,  2,  7,  8],
       [ 5,  6,  3,  4],
       [ 9, 10, 15, 16],
       [13, 14, 11, 12]])

In [268]:
# Mutation
def mutation(childs,p1=5,p2=10):
    for child in range(childs.shape[0]):
        rand1 = np.random.uniform(0,100)
        #print(rand1)
        if rand1 <= p1:
            for gen in range(childs.shape[1]):
                rand2 = np.random.uniform(0,100)
                #print(rand2)
                if rand2 <= p2:
                    childs[child][gen] = np.random.uniform(lower,upper)
    return childs

In [247]:
childs

array([[ 1.,  2.,  7.,  8.],
       [ 5.,  6.,  3.,  4.],
       [ 9., 10., 15., 16.],
       [13., 14., 11.,  0.]])

In [258]:
mutated_childs = mutation(childs)
mutated_childs

4.350758684147349
29.812784147290593
9.139203238964
50.14011260781799
36.93359405686364
38.6294311013885
16.649313527593023
50.78375462619202


array([[ 1.        , -0.12419134,  7.        ,  8.        ],
       [ 5.        ,  6.        ,  3.        ,  4.        ],
       [ 9.        , 10.        , 15.        , 16.        ],
       [13.        , 14.        , 11.        ,  0.        ]])

# Genetic Algorithm for (Real) Global Optimization

In [315]:
# Parameters
n = [10,20,50] # dimension
N = 20*n[0] # number of chromosomes in the population
M = 17*n[0] # number of gens 
lower = -5.12 # lower bound (The domain of x_i is [-5.12,5.12]) 
upper = 5.12 # upper bound 
n_parents = N//2
cutoff_point = M//2 # cutoff point for the crossover
e = 1 # epsilon for termination criteria
p1 = 5 # (%) probability of select a chromosome for mutation
p2 = 10 # (%) probability of select a gen for mutation
itermax = 3#200 # max generation

In [317]:
# INITIALIZATION
pop = init_population()
iteration = 0
finish = termination_criteria(pare,e,iteration,itermax)
history = {}
bests = []
worsts = []
while not finish:
    # EVALUATE
    evaluated = evaluation(pop,error)
    # TERMINATION CHECK
    finish = termination_criteria(evaluated,e,iteration,itermax)
    # GENETIC OPERATIONS
    # selection
    parents,best_index, worst_index = selection(n_parents,pop,evaluated)
    bests.append(evaluated[best_index])
    worsts.append(evaluated[worst_index])
    history[f'gen: {iteration}'] = {'best':(evaluated[best_index],pop[best_index]),
                                 'worst':(evaluated[worst_index],pop[worst_index])}
    # crossover
    childs = crossover(parents, cutoff_point)
    # mutation
    mutated_childs = mutation(childs,p1,p2)
    # REPLACEMENT
    pop = np.concatenate((parents,childs))
    #print(parents)
    # LOCAL TECHNIQUE
    # NEW GENERATION
    print(f'Generation {iteration}: ',f'\n\tBest:{evaluated[best_index]}',f'\n\tWorst:{evaluated[worst_index]}')
    iteration += 1

[[-1.35645869  0.41958443  1.73318873 ...  1.16662616 -1.90121442
  -1.80243605]
 [-3.83668556  3.9474663  -1.81114667 ... -4.67776528  0.79091224
   0.22817073]
 [ 0.86981773  4.34317238  2.26031695 ... -2.90708508  4.10449914
  -4.30056599]
 ...
 [ 0.9825912  -2.66343555  2.4140322  ...  4.48746761 -3.18767374
  -2.7870295 ]
 [ 2.7560736   0.17767264  4.6746383  ... -2.90138073 -4.84830783
  -1.09336548]
 [-3.88342107 -3.38312231  3.44143677 ... -3.71858181  1.79946648
   4.43631957]]
Generation 0:  
	Best:1480.217723491735 
	Worst:1445.6822745282825
[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 ...
 [-3.83668556  3.9474663   1.73318873 ...  1.16662616 -1.90121442
  -1.80243605]
 [-1.35645869  0.41958443 -1.81114667 ... -4.67776528  0.79091224
   0.22817073]
 [ 0.86981773  4.34317238 -2.42160653 ...  0.81688172  

In [312]:
print(bests)
history

[1745.7091464222003, 1279.5024520539578, 0.0, 0.0]


{'gen: 0': {'best': (1745.7091464222003,
   array([-2.64347862, -3.4556338 , -2.30256555,  0.89193336, -1.18506768,
           2.24432261,  3.35418398,  4.48106876,  3.79544521,  3.7743828 ,
          -0.4983014 , -4.51703737, -3.60572279, -2.43326747,  3.42167535,
           4.07507932,  3.67171721,  3.86592089, -4.52410492, -2.55385955,
           2.49484801, -2.43710266,  4.51794786, -1.27417129,  1.98803527,
          -3.88537703, -1.02570936, -5.10854343,  0.92177147,  4.82808623,
          -1.41469078, -0.15832593,  1.39273536, -3.62855817, -4.54648627,
          -4.79469115, -1.75734823, -1.59623346, -2.51414612, -4.06342245,
          -4.28656011,  0.38815169, -5.01829289, -0.94386274,  3.43181906,
           2.58861851, -4.41622846, -3.68040608, -4.2822897 , -0.6742062 ,
           2.25599396, -4.02760617,  3.3066263 ,  0.35880234, -1.95362157,
          -3.18457417, -2.55998132,  1.76646588, -3.11781621,  3.34853088,
          -1.45908859,  1.68865551, -1.86308739,  4.0311172

In [ ]:
# http://www.umsl.edu/cmpsci/about/People/Faculty/CezaryJanikow/folder%20two/Numerical.pdf